repository:
  name: mssql-demo
  description: description of repo
  topics: mssql, sqlpackage, dotnet
  private: true
  has_issues: false
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  enable_automated_security_fixes: true
  enable_vulnerability_alerts: true

collaborators:
  - username: abrocklesbykpmg
    permission: admin
  - username: qaraaslam
    permission: admin

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: false
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: [build]
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []
